[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_escrow = "8LfvCPX67gZ8hfz93BqG4T6PmGrADjCKixTxtUXG2QmF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/lyte/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
