[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter_airdrop = "7pmvFUXLvHyDb37LGJbBDsQgUCvarj3cx4qxM49Gdxfq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/lyte/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
